services:

  # Servicio de MariaDB
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_gdr
    restart: always
    ports:
      - "4306:3306"
    env_file:
      - .env
    environment:
      MARIADB_USER: aaee_gdr
      MARIADB_DATABASE: hogwarts_gdr
      MARIADB_PASSWORD: “1234”
      MARIADB_ROOT_PASSWORD: "1234"

  # Servicio de la Aplicación Spring Boot
  app:
    image: ghcr.io/GustavoEEDD/hogwarts_backend_992:latest
    container_name: aaee_hogwarts_app_gdr
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mariadb
